### ISSUE TITLE
Stata 13 Automation on Windows 10 

### ISSUE THREAD

**Issue by Michaelzjz** [mattiasnordin/StataEditor#14]
Hello Matt,

I am brand new to using Stata Editor. I set up the Stata Automation using the Vista instructions as you suggest. When I try to "do" or "run" my do file, there's no instance of Stata opened.
And I've  checked Stata would be launched when I opened the console and wrote:
`import win32com.client
win32com.client.Dispatch ("stata.StataOLEApp")
`
I'm using Stata 13.1.
Any advice?

And the error is as follows:
`unable to auto detect encoding for D:\学习与工作类\0-西财\大三\大三下\计量经济学\stata教学\4.12日\第一次上机.do, using fallback encoding Western (Windows 1252)
Traceback (most recent call last):
  File "StataEditorPlugin in C:\Users\张继中\AppData\Roaming\Sublime Text 3\Installed Packages\StataEditor.sublime-package", line 39, in StataAutomate
AttributeError: 'module' object has no attribute 'stata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\软件安装\2-Sublime Text\Sublime Text 3\sublime_plugin.py", line 568, in run_
    return self.run(edit, **args)
  File "StataEditorPlugin in C:\Users\张继中\AppData\Roaming\Sublime Text 3\Installed Packages\StataEditor.sublime-package", line 103, in run
  File "StataEditorPlugin in C:\Users\张继中\AppData\Roaming\Sublime Text 3\Installed Packages\StataEditor.sublime-package", line 42, in StataAutomate
pywintypes.error: (2, 'WinExec', '系统找不到指定的文件。')
`

**Comment by mattiasnordin** [comment]
I saw that you closed this issue, does that mean that it is working now?

**Comment by Michaelzjz** [comment]
Yes,I've changed my Stata in an English path, and then it can work.
Thanks for caring.

**Comment by mattiasnordin** [comment]
Great!
