### ISSUE TITLE
Stata13 in Windows 10 not working

### ISSUE THREAD

**Issue by ryanwcho** [mattiasnordin/StataEditor#31]
Hello! I've never had StataEditor work, but I'm trying to do it once again.

The below is the issue I continue to get. 

`KeyError: 'Selection'
Unable to open /C/Users/*/AppData/Roaming/Sublime Text 3/Packages/StataEditor/StataEditor.sublime-settings
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1066, in run_
    return self.run(edit, **args)
  File "C:\Users\*\AppData\Roaming\Sublime Text 3\Installed Packages\StataEditor.sublime-package\StataEditorPlugin.py", line 145, in run
KeyError: 'Selection'`

**Comment by mattiasnordin** [comment]
Hi,
Sorry for the late response. Have you looked at issues #8 or #13, could possibly be related. The first thing to check is whether automation is set up properly. To do so, open the console in Sublime Text and write the following:

`import win32com.client`
`win32com.client.Dispatch ("stata.StataOLEApp")`

Is Stata launched when you do this? If not, what type of error message do you get?
