### ISSUE TITLE
Windows 10 2004 and Stata 16.1 execution failure (likely similar to #37)

### ISSUE THREAD

**Issue by justinsola** [mattiasnordin/StataEditor#42]
After a re-install of windows, StataEditor now longer works on my desktop computer. Stata IC version 16.1, all instructions followed (including using the SSC package sublime to try and automate setup). Console errors outputted in ST3 are as follows:

```
Traceback (most recent call last):
  File "C:\Users\justi\AppData\Roaming\Sublime Text 3\Installed Packages\StataEditor.sublime-package\StataEditorPlugin.py", line 63, in StataAutomate
AttributeError: 'module' object has no attribute 'stata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1082, in run_
    return self.run(edit, **args)
  File "C:\Users\justi\AppData\Roaming\Sublime Text 3\Installed Packages\StataEditor.sublime-package\StataEditorPlugin.py", line 158, in run
  File "C:\Users\justi\AppData\Roaming\Sublime Text 3\Installed Packages\StataEditor.sublime-package\StataEditorPlugin.py", line 66, in StataAutomate
pywintypes.error: (2, 'WinExec', 'The system cannot find the file specified.')
```

Any insight? Thanks so much!

_Originally posted by @justinsola in https://github.com/mattiasnordin/StataEditor/issues/37#issuecomment-693754407_

**Comment by justinsola** [comment]
I solved this issue by changing sublime text to run as administrator!
