### ISSUE TITLE
Sublime suddenly can't call out the Stata.

### ISSUE THREAD

**Issue by ZHULOO** [mattiasnordin/StataEditor#50]
I have been working on it ,suddenly sublime stop working, The console information is displayed as below: 
Traceback (most recent call last):
  File "D:\Program Files\Sublime Text 3\Data\Installed Packages\StataEditor.sublime-package\StataEditorPlugin.py", line 63, in StataAutomate
AttributeError: 'module' object has no attribute 'stata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Sublime Text 3\sublime_plugin.py", line 1082, in run_
    return self.run(edit, **args)
  File "D:\Program Files\Sublime Text 3\Data\Installed Packages\StataEditor.sublime-package\StataEditorPlugin.py", line 158, in run
  File "D:\Program Files\Sublime Text 3\Data\Installed Packages\StataEditor.sublime-package\StataEditorPlugin.py", line 66, in StataAutomate
pywintypes.error: (2, 'WinExec', 'The system could not find the specified file.')

**Comment by timat35** [comment]
I think you should reinstall [stata automation] (https://www.stata.com/automation/#install)

If not working try to follow all steps here
https://marketplace.visualstudio.com/items?itemName=Yeaoh.stataRun

but it should not be link

**Comment by ZHULOO** [comment]
Thanks you all the same , I have tried all the methods, but it doesn't work. finally I reinstall the Windows10, The things goes well, So, I think it 's the os's problem, it's not the stataeditor's problem.
